[package]
name = "aam-rs"
version = "1.0.0"
description = "A Rust implementation of the Abstract Alias Mapping (AAM) framework for aliasing and maping aam files."
license = "MIT"
repository = "https://github.com/INiNiONC/aam-rs/"
edition = "2024"
readme = "README.md"

[dependencies]
